#!/bin/bash

source .venv/bin/activate
export FLASK_APP=app
export FLASK_DEBUG=1

echo "Finished setting up env"
flask run

# Setup run (only very first time)
#   chmod +x run

# To run run
#   ./run
